### ISSUE TITLE
[Azure]  First try issues report

### ISSUE THREAD

**Issue by yuxisun1217** [virt-s1/perf-agent#10]
1. pbench-fio.wrapper script needs +x permission
2. '# ./test.sh (this is the script of run fio commands in README)
**what's this? []** (not sure what is this line? Cannot see it in the second run)
Collecting system information
[error][2021-02-09T07:17:39.667369571] [pbench-sysinfo-dump]**sosreport collection failed!** (do I miss any package?)
3. /var/lib/pbench-agent/fio_Azure_RHEL-8.4.0-20210201.n.0_x86_bios_tempdisk_280_D210209T073954_2021.02.09T07.39.54/1-read-4KiB/sample1/fio.cmd: line 1: **/usr/local/bin/fio: No such file or directory** (The correct path is /usr/bin/fio)

**Comment by schrht** [comment]
For the thrid one, please manually add a soft link (` ln -s /usr/local/bin/fio /usr/bin/fio`) to work around this issue. It was a known issue of pbench-agent.

**Comment by schrht** [comment]
For the second one, please help check if you have successfully installed `sosreport` package, or provide an instance for me to check it. Thanks!

**Comment by yuxisun1217** [comment]
> ln -s /usr/local/bin/fio /usr/bin/fio

Thanks! 
BTW, should be "ln -s /usr/bin/fio /usr/local/bin/fio" :)

**Comment by schrht** [comment]
Will fix the `+x` one and the README.

**Comment by schrht** [comment]
Issue 1 has been fixed. Issue 2 and 3 are known issues of pbench-agent.
So close this thread now.
